version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    working_directory: ~/go/src/github.com/taeho-io/idl
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Generate
          command: |
            make clean
            make generate
      - run:
          name: Diff
          command: make diff
